# Utilisez une image de base Node.js
FROM node:22-alpine as build

# Définissez le répertoire de travail
WORKDIR /usr/src/app

# Copiez les fichiers package.json et package-lock.json
COPY package*.json ./

# Installez les dépendances
RUN npm install

# Copiez le reste des fichiers de l'application
COPY . .

# Construisez l'application
RUN npm run build

# Utilisez une image nginx pour servir l'application construite
FROM nginx:alpine

# Copiez les fichiers de build dans le répertoire par défaut de nginx
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Exposez le port sur lequel l'application écoute
EXPOSE 3000

# Commande pour démarrer le serveur nginx
CMD ["nginx", "-g", "daemon off;"]
