# Utilisez une image de base Node.js version 22 légère
FROM node:22-slim

# Définissez le répertoire de travail
WORKDIR /app

# Copiez les fichiers package.json et package-lock.json
COPY package*.json ./

# Installez les dépendances
RUN npm install --legacy-peer-deps

# Copiez le reste des fichiers de l'application
COPY . .

# Exposez le port sur lequel l'application écoute
EXPOSE 3001

# Commande pour démarrer l'application
CMD ["npm", "start"]
